sudo: required

services:
    - docker

before_install:
#    - docker build . -t zleba/rootlhapdf 
    - cd system && docker build . --cache-from  zleba/rootlhapdf:system -t zleba/rootlhapdf:system && cd ..
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push zleba/rootlhapdf:system
#    - cd ..     && docker build . --cache-from  zleba/rootlhapdf:latest -t zleba/rootlhapdf:latest
#    - docker push zleba/rootlhapdf:latest
#    - docker images

script:
#Compile it
    - cd exerciseCpp
    - ./rd make -j2 all

#Test it
    - ./rd ./example-1 | tee example1.txt
    - ./rd ./example-2 | tee example2.txt
    - ./rd ./example-3 | tee example3.txt
    - ./rd ./example-4 | tee example4.txt
    - ./rd ./example-5 | tee example5.txt
    - ./rd ./example-lhapdf | tee examplelhapdf.txt
    - ./rd ./example-6 | tee example6.txt
    - ./rd ./example-7 | tee example7.txt
    - ./rd ./example-8 | tee example8.txt
    - ./rd ./example-9 | tee example9.txt

    - mkdir -p ../public/cpp
    - cp *.pdf *.txt ../public/cpp
    - ls ../public/cpp/*

#Test Py
    - cd ..
    - ./rd make allRun
    - mkdir -p  public/Nb public/NbExec
    - cp exerciseNb/*.ipynb   public/Nb
    - cp exerciseNbExec/*.ipynb   public/NbExec

    - git config user.email radek.zlebcik@gmail.com
    - git config user.name zleba
    - git checkout master
    - git add exerciseNb/*.ipynb exerciseNbExec/*.ipynb
    - git commit -m "robot add [ci skip]" | true
    - git push  "https://${GITHUB_TOKEN}@github.com/zleba/mcSchool.git" master 


deploy:
  provider: pages
  local-dir : public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: false
  on:
    branch: master



