sudo: required

services:
    - docker

before_install:
    - docker pull zleba/rootlhapdf
    - docker images


script:
    - cd exercise1
    - ./runDocker make -j2 all
    - cd ../exercise2
    - ./runDocker make -j2 all
    - cd ../exercise3
    - ./runDocker make -j2 all

    - cd ../exercise1
    - ./runDocker ./example-1
    - ./runDocker ./example-2
    - ./runDocker ./example-3
    - ./runDocker ./example-4
    - ./runDocker ./example-5
    - ./runDocker ./example-lhapdf
    - cd ..
    - mkdir public
    - cp exercise1/*.pdf public
    - ls public/*

deploy:
  provider: pages
  local-dir : public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master



#jobs:
#    include:
#        - stage: build
#        script:
#        - cd exercise1
#        - ./runDocker make -j2 all
#        - cd ../exercise2
#        - ./runDocker make -j2 all
#        - cd ../exercise3
#        - ./runDocker make -j2 all
#        - stage: run
#        script:
#        - cd ../exercise1
#        - ./runDocker ./example-1
#        - ./runDocker ./example-2
#        - ./runDocker ./example-3
