sudo: required

services:
    - docker

before_install:
    - docker pull zleba/rootlhapdf
    - docker images

script:
    - cd exercise1
    - ./runDocker make exercise-1
    - ./runDocker ./example-1
