sudo: required

services:
    - docker

before_install:
    - docker build . -t zleba/rootlhapdf 
#    - docker pull zleba/rootlhapdf
    - docker images


script:
#Compile it
    - cd exerciseCpp
    - ./rd make -j2 all

#Test it
    - ./rd ./example-1 | tee example1.txt
    - ./rd ./example-2 | tee example2.txt
    - ./rd ./example-3 | tee example3.txt
    - ./rd ./example-4 | tee example4.txt
    - ./rd ./example-5 | tee example5.txt
    - ./rd ./example-lhapdf | tee examplelhapdf.txt
    - ./rd ./example-6 | tee example6.txt
    - ./rd ./example-7 | tee example7.txt
    - ./rd ./example-8 | tee example8.txt
    - ./rd ./example-9 | tee example9.txt

    - mkdir -p ../public/cpp
    - cp *.pdf *.txt ../public/cpp
    - ls ../public/cpp/*

#Test Py
    - cd ..
    - ./rd make exerciseHtml/example-1.html
    - ./rd make exerciseHtml/example-2.html
    - ./rd make exerciseHtml/example-3.html
    - mkdir -p ../public/Html
    - cp exerciseHtml/*.html  ../public/Html


deploy:
  provider: pages
  local-dir : public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: false
  on:
    branch: master



