sudo: required

services:
    - docker

before_install:
    - docker pull zleba/rootlhapdf
    - docker images

script:
    - cd exercise1
    - ./runDocker make -j2 all
    - ./runDocker ./example-1
    - ./runDocker ./example-2
    - ./runDocker ./example-3
    - cd ../exercise2
    - ./runDocker make -j2 all
    - cd ../exercise3
    - ./runDocker make -j2 all
